### ISSUE TITLE
Finalize and make pull request into Laravel

### ISSUE THREAD

**Issue by decadence** [sleeping-owl/with-join#14]
Hello, thanks for the great extension.

But why didn't you make this functionality available for hasOne (possibly for ManyToMany) relationships?

When I started learning Laravel I was very surprised it doesn't support filtering and ordering by related tables with simple dot syntax (like Kohana does):
$query->with("relation")->where("relation.relation_column", "=", "example")->order_by("relation.name", "asc").

So easy and intuitive.

And why don't you want make pull request to Laravel core? I bet many people would appreciate it, because now is only way to sort by related colums is using joins manually. I think Laravel must have much easier way to do it.

Filtering via whereHas generate subquery with count, instead of using joins.

For example: https://github.com/laravel/framework/issues/6363
and https://github.com/laravel/framework/issues/4200

Can you please do it?

P.S. Привет с Хабра :)

**Comment by decadence** [comment]
Another issue about whereHas and Joins
https://github.com/laravel/framework/issues/3543

**Comment by GreenLamantin** [comment]
+1

**Comment by Ardakilic** [comment]
+1
